lang: EN
counry: US

redis:
  host: localhost
  port: 6379

data:
  path: data

articles:
  path: articles

collections:
  sample: 
    path: "*.xml"
  full: 
    path: "*.xml"
  supplementjune2014:
    path: "*.xml"
  pages:
    path: "*.xml"
