source 'http://gemcutter.org'
source 'http://gems.github.com' 

gem 'json'
gem 'debugger'
gem 'uuid'
gem 'feedzirra'
gem 'sanitize'
gem 'rspec'
gem 'redis'
gem 'confstruct'
gem 'eventmachine'
gem 'em-hiredis'